en/reference/rdkafka/rdkafka/producer/construct.xml, en/reference/rdkafka/rdkafka/setloglevel.xml
Tiny updates for documentation.
=> Docs fixes

en/reference/rdkafka/examples/producer.xml
=> Fix bad link

en/reference/rdkafka/examples/high-level-consumer.xml
=> Fix some typo

en/reference/rdkafka/versions.xml
=> add version for getCommitedOffsets

en/reference/rdkafka/rdkafka/topicconf/set.xml
this should fix https://github.com/arnaud-lb/php-rdkafka/issues/129
=> fix topic conf set parameters

en/reference/rdkafka/configure.xml
https://github.com/arnaud-lb/php-rdkafka/issues/159
=> add hint about dll and php versions

en/reference/rdkafka/rdkafka/kafkaconsumertopic/offsetstore.xml
@arnaud-lb last time it seems the merge changes were not deployed, i opened an issue, maybe something went wrong, just as as info for you. Thanks in advance! :smile_cat: 
https://github.com/arnaud-lb/php-rdkafka/issues/178
=> add note about config setting

en/reference/rdkafka/rdkafka.xml, en/reference/rdkafka/rdkafka/offsetsfortimes.xml, en/reference/rdkafka/rdkafka/querywatermarkoffsets.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/219
https://github.com/arnaud-lb/php-rdkafka/issues/130
=> add doc for offsetsForTimes and queryWatermarkOffsets

en/reference/rdkafka/examples/high-level-consumer.xml, en/reference/rdkafka/rdkafka/conf/setdefaulttopicconf.xml, en/reference/rdkafka/rdkafka/kafkaconsumer/assign.xml, en/reference/rdkafka/rdkafka/kafkaconsumer/subscribe.xml
https://github.com/arnaud-lb/php-rdkafka/pull/266
=> deprecate setDefaultTopicConf (doc)

en/reference/rdkafka/constants.xml
https://github.com/arnaud-lb/php-rdkafka/pull/267
=> add partitioner constants (doc)

en/reference/rdkafka/rdkafka/conf/setlogcb.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/253
=> add log cb (doc)

en/reference/rdkafka/setup.xml
https://github.com/arnaud-lb/php-rdkafka/issues/269
=> update setup doc

en/reference/rdkafka/rdkafka/kafkaconsumer/offsetsfortimes.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/270
=> add offsetsForTimes high level (doc)

en/reference/rdkafka/rdkafka.xml, en/reference/rdkafka/rdkafka/consumer/newqueue.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/273
=> move newQueue to consumer (doc)

en/reference/rdkafka/rdkafka.message.xml
Based on: 
https://github.com/arnaud-lb/php-rdkafka/blob/e459be62e3c1/message.c#L146-L162
=> Add missing properties to RdKafka\Message class

en/reference/rdkafka/rdkafka/kafkaconsumer/querywatermarkoffsets.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/271
=> add queryWatermarkOffsets for high level (doc)

en/reference/rdkafka/rdkafka/consumertopic/consumebatch.xml, en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/pull/256
=> add batch consume (doc)

en/reference/rdkafka/configure.xml
https://github.com/arnaud-lb/php-rdkafka/issues/287
=> remove outdated osx installation

en/reference/rdkafka/examples/producer.xml, en/reference/rdkafka/rdkafka/producertopic/produce.xml, en/reference/rdkafka/rdkafka/producertopic/producev.xml
https://github.com/arnaud-lb/php-rdkafka/issues/292 https://github.com/arnaud-lb/php-rdkafka/pull/264
@arnaud-lb to stress the proper shutdown in `rdkafka:4.0` a bit more
=> improve producer doc

en/reference/rdkafka/versions.xml
https://github.com/arnaud-lb/php-rdkafka/issues/300
=> fix lib version for purge

en/reference/rdkafka/rdkafka/kafkaconsumer/consume.xml
https://github.com/arnaud-lb/php-rdkafka/issues/337
=> fix param type

en/reference/rdkafka/rdkafka/consumertopic/consumecallback.xml, en/reference/rdkafka/versions.xml
add doc for https://github.com/arnaud-lb/php-rdkafka/issues/242 https://github.com/arnaud-lb/php-rdkafka/pull/310
=> add callback doc

en/reference/rdkafka/rdkafka.topicconf.xml
To help avoid confusions, link to the topic conf in the doc directly
https://github.com/arnaud-lb/php-rdkafka/issues/353
=> adjust link

en/reference/rdkafka/rdkafka/topicpartition/construct.xml
https://github.com/arnaud-lb/php-rdkafka/issues/345
=> fix toppar construct default value doc

en/reference/rdkafka/rdkafka/producertopic/producev.xml
relates to: https://github.com/kwn/php-rdkafka-stubs/issues/28
=> add missing producev param
